name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sqlite3 dependency
      run: apt-get install libsqlite3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
